name: ecdoc
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_info_plus: ^12.2.0

  http: ^1.5.0
  crypto: ^3.0.2

  #  provider: ^6.1.5+1


# ------------------- Jemi's code
  # Fonts
  google_fonts: ^6.3.2

  # State management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.0.0
  injectable: ^2.5.0

  # Local Database
  drift: ^2.20.0
  drift_dev: ^2.20.0
  sqlite3_flutter_libs: ^0.5.40
  shared_preferences: ^2.5.3

  # Network
  dio: ^5.4.3+1
  retrofit: ^4.0.3
  json_annotation: ^4.9.0

  # Firebase
#  firebase_core: ^3.8.0
#  firebase_auth: ^5.3.0
#  firebase_messaging: ^15.0.0
#  flutter_local_notifications: ^17.2.0

  # Utilities
  intl: ^0.20.2
  logger: ^2.2.0
  freezed_annotation: ^3.0.0
  json_serializable: ^6.7.0
  image_picker: ^1.2.0
  flutter_screenutil: ^5.9.3
  not_static_icons: ^0.8.0
  fl_chart: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# ------------------------- Jemi's code
  build_runner: ^2.4.10
  retrofit_generator: ^10.0.6
  injectable_generator: ^2.6.0
  freezed: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/

